<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class AccessoriesProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accessories = [
            ['name' => 'BLACK HANDLE PLASTIC', 'color' => null, 'quantity' => 102],
            ['name' => 'WHITE HANDLE PLASTIC', 'color' => null, 'quantity' => 69],
            ['name' => 'TRADITIONAL CAM HANDLE LEFT', 'color' => 'HA - HITOMI', 'quantity' => 101],
            ['name' => 'TRADITIONAL CAM HANDLE LEFT', 'color' => 'PCW', 'quantity' => 4],
            ['name' => 'ELEGANT HANDLE', 'color' => 'HA - ELEGANT', 'quantity' => 16],
            ['name' => 'ELEGANT HANDLE', 'color' => 'PCW - ELEGANT', 'quantity' => 27],
            ['name' => 'CABINET HANDLE', 'color' => null, 'quantity' => 17],
            ['name' => 'LATCH KEEPER SMALL', 'color' => 'HA', 'quantity' => 371],
            ['name' => 'LATCH KEEPER SMALL', 'color' => 'PCW', 'quantity' => 600],
            ['name' => 'LATCH KEEPER BIG', 'color' => 'HA', 'quantity' => 158],
            ['name' => 'LATCH KEEPER BIG', 'color' => 'PCW', 'quantity' => 406],
            ['name' => 'FLUSH HANDLE', 'color' => 'HA - HITOMI', 'quantity' => 154],
            ['name' => 'FLUSH HANDLE', 'color' => 'PCW - HITOMI', 'quantity' => 66],
            ['name' => 'FLUSH HANDLE', 'color' => 'HA - MATEX', 'quantity' => 9],
            ['name' => 'FLUSH HANDLE', 'color' => 'PCW - MATEX', 'quantity' => 5],
            ['name' => 'FLUSH HANDLE', 'color' => 'PCW - DAH LING', 'quantity' => 1],
            ['name' => 'FLUSH LOCK', 'color' => 'PCW - HITOMI', 'quantity' => 1],
            ['name' => 'FLUSH LOCK', 'color' => 'HA - HITOMI', 'quantity' => 236],
            ['name' => 'FLUSH LOCK', 'color' => 'A - HITOMI', 'quantity' => 1],
            ['name' => 'FLUSH LOCK', 'color' => 'HA - MATEX', 'quantity' => 175],
            ['name' => 'FLUSH LOCK', 'color' => 'PCW - MATEX', 'quantity' => 214],
            ['name' => 'FLUSH LOCK', 'color' => 'HA - ELEGANT', 'quantity' => 1],
            ['name' => 'FLUSH LOCK', 'color' => 'PCW - ELEGANT', 'quantity' => 1],
            ['name' => 'FLUSH BOLT', 'color' => 'HA - HITOMI', 'quantity' => 229],
            ['name' => 'FLUSH BOLT', 'color' => 'PCW - HITOMI', 'quantity' => 7],
            ['name' => 'FLUSH BOLT', 'color' => 'HA - ELEGANT', 'quantity' => 93],
            ['name' => 'FLUSH BOLT', 'color' => 'PCW - ELEGANT', 'quantity' => 50],
            ['name' => 'FLUSH BOLT', 'color' => 'HA - MATEX', 'quantity' => 92],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'HA - HITOMI', 'quantity' => 1],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'PCW - HITOMI', 'quantity' => 1],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'A - HITOMI', 'quantity' => 1],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'HA - MATEX', 'quantity' => 170],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'PCW - MATEX', 'quantity' => 150],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'HA - ELEGANT', 'quantity' => 168],
            ['name' => 'FLUSH LOCK W/KEY', 'color' => 'PCW - ELEGANT', 'quantity' => 150],
            ['name' => 'BENDED HANDLE', 'color' => 'HA', 'quantity' => 676],
            ['name' => 'BENDED HANDLE', 'color' => 'A', 'quantity' => 29],
            ['name' => 'BENDED HANDLE', 'color' => 'PCW', 'quantity' => 61],
            ['name' => 'CAM HANDLE RIGHT', 'color' => 'HA - HITOMI', 'quantity' => 50],
            ['name' => 'CAM HANDLE RIGHT', 'color' => 'PCW - HITOMI', 'quantity' => 67],
            ['name' => 'SAMSON HANDLE', 'color' => 'HA', 'quantity' => 67],
            ['name' => 'SAMSON HANDLE', 'color' => 'A', 'quantity' => 1],
            ['name' => 'SAMSON HANDLE', 'color' => 'BROWN', 'quantity' => 5],
            ['name' => 'SAMSON HANDLE', 'color' => 'PCW', 'quantity' => 83],
            ['name' => 'NYLON ROLLER SINGLE', 'color' => 'HITOMI', 'quantity' => 488],
            ['name' => 'NYLON ROLLER DOUBLE', 'color' => 'HITOMI', 'quantity' => 38],
            ['name' => 'NYLON ROLLER SINGLE', 'color' => 'MATEX', 'quantity' => 201],
            ['name' => 'PLASTIC ROLLER SINGLE', 'color' => null, 'quantity' => 234],
            ['name' => 'PLASTIC ROLLER DOUBLE', 'color' => null, 'quantity' => 216],
            ['name' => 'NYLON ROLLER W/BEARING', 'color' => null, 'quantity' => 61],
            ['name' => 'N-ROLLER DOUBLE ORDINARY', 'color' => 'HITOMI', 'quantity' => 1],
            ['name' => 'STEEL ROLLER SINGLE', 'color' => null, 'quantity' => 256],
            ['name' => 'STEEL ROLLER DOUBLE', 'color' => null, 'quantity' => 16],
            ['name' => 'HALFMOON ROLLER', 'color' => null, 'quantity' => 114],
            ['name' => 'BARREL BOLT', 'color' => 'HA', 'quantity' => 182],
            ['name' => 'BARREL BOLT', 'color' => 'A', 'quantity' => 19],
            ['name' => 'BARREL BOLT', 'color' => 'PCW', 'quantity' => 100],
            ['name' => 'HINGES 1/2X2', 'color' => null, 'quantity' => 1],
            ['name' => 'HINGES 1/2X3', 'color' => 'HA', 'quantity' => 406],
            ['name' => 'HINGES 1/2X3', 'color' => 'PCW', 'quantity' => 161],
            ['name' => 'HINGES BIG', 'color' => 'A', 'quantity' => 187],
            ['name' => 'HINGES SMALL', 'color' => 'A', 'quantity' => 40],
            ['name' => 'TUBE DOOR CLOSER', 'color' => 'HA', 'quantity' => 41],
            ['name' => 'TUBE DOOR CLOSER', 'color' => 'A', 'quantity' => 26],
            ['name' => 'ARM DOOR CLOSER', 'color' => 'HA', 'quantity' => 8],
            ['name' => 'ARM DOOR CLOSER', 'color' => 'A', 'quantity' => 11],
            ['name' => 'ARM DOOR CLOSER', 'color' => 'PCW', 'quantity' => 1],
            ['name' => 'BALANCER', 'color' => 'HA', 'quantity' => 507],
            ['name' => 'BALANCER', 'color' => 'A', 'quantity' => 71],
            ['name' => 'MAGNETIC CATCHES', 'color' => 'Brown', 'quantity' => 85],
            ['name' => 'MAGNETIC HINGES SINGLE', 'color' => null, 'quantity' => 1],
            ['name' => 'MAGNETIC HINGES DOUBLE', 'color' => null, 'quantity' => 21],
            ['name' => 'WF LOCKSET', 'color' => 'HA', 'quantity' => 157],
            ['name' => 'WF LOCKSET', 'color' => 'A', 'quantity' => 68],
            ['name' => 'WF LOCKSET', 'color' => 'PCW', 'quantity' => 1],
            ['name' => 'WF LOCKSET', 'color' => 'HA - SEA STAR', 'quantity' => 1],
            ['name' => 'ALPALOCK', 'color' => 'HA', 'quantity' => 68],
            ['name' => 'ALPALOCK', 'color' => 'A', 'quantity' => 7],
            ['name' => 'ALPALOCK', 'color' => 'PCW', 'quantity' => 1],
            ['name' => 'SHOWCASE LOCK', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'DRAWER LOCK', 'color' => 'TOP GRADE', 'quantity' => 11],
            ['name' => 'SCREEN FRAME CORNER LOCK', 'color' => null, 'quantity' => 250],
            ['name' => 'SCREEN HOOK LOCK', 'color' => null, 'quantity' => 204],
            ['name' => 'PITO GUIDE', 'color' => null, 'quantity' => 1],
            ['name' => 'HOOK AND EYE', 'color' => 'OFS', 'quantity' => 1],
            ['name' => 'HOOK AND EYE', 'color' => 'SMALL', 'quantity' => 1],
            ['name' => 'L-300 LOCK', 'color' => null, 'quantity' => 1],
            ['name' => 'GLASS SHELVES', 'color' => null, 'quantity' => 1],
            ['name' => 'SHELVES HOLDER', 'color' => null, 'quantity' => 147],
            ['name' => 'TOX #5 FEET', 'color' => null, 'quantity' => 7],
            ['name' => 'TOX #5 PACKED', 'color' => 'WHITE', 'quantity' => 100],
            ['name' => 'TOX #5 PACKED SMALL', 'color' => 'BROWN', 'quantity' => 1],
            ['name' => 'TOX #5', 'color' => 'BROWN', 'quantity' => 499],
            ['name' => 'PLASTIC CAP', 'color' => null, 'quantity' => 667],
            ['name' => 'CORNER LOCK', 'color' => null, 'quantity' => 1],
            ['name' => 'TRADITIONAL CORNER BRACKET W/ SCREW', 'color' => null, 'quantity' => 1622],
            ['name' => 'PUSH BRACKET', 'color' => 'WHITE', 'quantity' => 1],
            ['name' => 'PUSH BRACKET', 'color' => 'A', 'quantity' => 1],
            ['name' => 'PUSH BRACKET', 'color' => 'HA', 'quantity' => 1],
            ['name' => 'SPRAY PAINT', 'color' => 'WHITE', 'quantity' => 1],
            ['name' => 'SPRAY PAINT', 'color' => 'BLACK', 'quantity' => 1],
            ['name' => 'DRILL BIT 6MM', 'color' => null, 'quantity' => 1],
            ['name' => 'DRILL BIT MASON 3/16 LONG', 'color' => null, 'quantity' => 1],
            ['name' => 'OVERHEAD DOOR CLOSER', 'color' => 'MIST', 'quantity' => 1],
            ['name' => 'OVERHEAD DOOR CLOSER', 'color' => 'GMT', 'quantity' => 16],
            ['name' => 'FLOOR HINGE', 'color' => 'GMT', 'quantity' => 1],
            ['name' => '4BAR HINGES SIDE OPEN #8', 'color' => 'MIST', 'quantity' => 24],
            ['name' => '4BAR HINGES SIDE OPEN #10', 'color' => 'HITOMI', 'quantity' => 404],
            ['name' => '4BAR HINGES SIDE OPEN #12', 'color' => 'MIST', 'quantity' => 4],
            ['name' => '4BAR HINGES SIDE OPEN #14', 'color' => 'HITOMI', 'quantity' => 100],
            ['name' => '4BAR HINGES SIDE OPEN #14', 'color' => 'MIST', 'quantity' => 1],
            ['name' => '4BAR HINGES SIDE OPEN #16', 'color' => 'MIST', 'quantity' => 200],
            ['name' => '4BAR HINGES SIDE OPEN #18', 'color' => 'HITOMI', 'quantity' => 1],
            ['name' => '4BAR HINGES CENTER OPEN #8', 'color' => 'MIST', 'quantity' => 101],
            ['name' => '4BAR HINGES CENTER OPEN #10', 'color' => 'MIST', 'quantity' => 14],
            ['name' => '4BAR HINGES CENTER OPEN #12', 'color' => 'MIST', 'quantity' => 404],
            ['name' => '4BAR HINGES CENTER OPEN #14', 'color' => 'MIST', 'quantity' => 294],
            ['name' => '4BAR HINGES CENTER OPEN #16', 'color' => 'HITOMI', 'quantity' => 1],
            ['name' => '4BAR HINGES CENTER OPEN #16', 'color' => 'MIST', 'quantity' => 407],
            ['name' => 'GLAZING', 'color' => 'BLACK', 'quantity' => 1],
            ['name' => 'GLAZING', 'color' => 'WHITE', 'quantity' => 30],
            ['name' => 'GLAZING', 'color' => 'GRAY', 'quantity' => 1],
            ['name' => 'GLAZING', 'color' => 'BROWN', 'quantity' => 1],
            ['name' => 'DOWSIL SEALANT', 'color' => 'BROWN', 'quantity' => 6],
            ['name' => 'DOWSIL SEALANT', 'color' => 'WHITE', 'quantity' => 12],
            ['name' => 'DOWSIL SEALANT CLEAR', 'color' => 'CLEAR', 'quantity' => 1],
            ['name' => 'DOWSIL SEALANT', 'color' => 'BLACK', 'quantity' => 1],
            ['name' => 'SEASTAR SEALANT', 'color' => 'BROWN', 'quantity' => 91],
            ['name' => 'SEASTAR SEALANT', 'color' => 'WHITE', 'quantity' => 201],
            ['name' => 'SEASTAR SEALANT', 'color' => 'BLACK', 'quantity' => 298],
            ['name' => 'SEASTAR SEALANT', 'color' => 'CLEAR', 'quantity' => 125],
            ['name' => 'RIVETS 1/8 X 1/2', 'color' => 'HA', 'quantity' => 19],
            ['name' => 'RIVETS 1/8 X 1/2', 'color' => 'A', 'quantity' => 10],
            ['name' => 'RIVETS 1/8 X 1/2', 'color' => 'PCW', 'quantity' => 10],
            ['name' => 'RIVETS 1/8 X 3/4', 'color' => 'A', 'quantity' => 1],
            ['name' => 'RIVETS 3/16', 'color' => 'A', 'quantity' => 1],
            ['name' => 'SD MOHAIR', 'color' => null, 'quantity' => 1],
            ['name' => 'ED MOHAIR', 'color' => null, 'quantity' => 1],
            ['name' => 'RUBBER W/LOCK', 'color' => null, 'quantity' => 4],
            ['name' => 'VINYL 1/2', 'color' => null, 'quantity' => 1],
            ['name' => 'VINYL #1', 'color' => null, 'quantity' => 5],
            ['name' => 'VINYL #2', 'color' => null, 'quantity' => 0],
            ['name' => 'VINYL #3', 'color' => null, 'quantity' => 1],
            ['name' => 'VINYL #4', 'color' => null, 'quantity' => 1],
            ['name' => 'VINYL W/ PIN', 'color' => null, 'quantity' => 1],
            ['name' => 'VINYL #1 BY ROLL', 'color' => null, 'quantity' => 1],
            ['name' => 'VINYL #2 BY ROLL', 'color' => null, 'quantity' => 1],
            ['name' => 'NORTON', 'color' => null, 'quantity' => 100],
            ['name' => 'PUMBELT', 'color' => null, 'quantity' => 1],
            ['name' => 'HOOK LOCK', 'color' => 'A', 'quantity' => 1],
            ['name' => 'HOOK LOCK', 'color' => 'HA', 'quantity' => 1],
            ['name' => 'GLASS LOCK W/SIDE', 'color' => null, 'quantity' => 20],
            ['name' => 'PATCH LOCK', 'color' => 'GMT', 'quantity' => 2],
            ['name' => 'PATCH FITTING', 'color' => null, 'quantity' => 1],
            ['name' => 'WOOD SCREW 8 X 1/2', 'color' => null, 'quantity' => 1],
            ['name' => 'WOOD SCREW 8 X 1', 'color' => null, 'quantity' => 10],
            ['name' => 'WOOD SCREW 8 X 1 1/2', 'color' => 'A', 'quantity' => 50],
            ['name' => 'WOOD SCREW 8 X 2', 'color' => null, 'quantity' => 0],
            ['name' => 'WOOD SCREW 8 X 3', 'color' => null, 'quantity' => 1],
            ['name' => 'WOOD SCREW 10 X 3', 'color' => null, 'quantity' => 1],
            ['name' => 'FLATHEAD 1/4 X 1 1/2', 'color' => null, 'quantity' => 1],
            ['name' => 'SILVER WOOD SCREW 8 X 1 1/2', 'color' => null, 'quantity' => 1],
            ['name' => 'SILVER WOOD SCREW 12 X 3', 'color' => null, 'quantity' => 1],
            ['name' => 'METAL CAP SCREW', 'color' => null, 'quantity' => 50],
            ['name' => 'METAL SCREW 8 X 1/2', 'color' => 'A', 'quantity' => 34],
            ['name' => 'METAL SCREW 8 X 1/2', 'color' => 'HA', 'quantity' => 56],
            ['name' => 'METAL SCREW 8 X 1/2', 'color' => 'BROWN - BY 1 GROSS', 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 1/2', 'color' => 'NULL', 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 1', 'color' => null, 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 1', 'color' => 'A', 'quantity' => 100],
            ['name' => 'METAL SCREW 8 X 1', 'color' => 'HA', 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 3/4', 'color' => null, 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 1 1/2', 'color' => 'HA', 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 1 1/2', 'color' => 'A', 'quantity' => 20],
            ['name' => 'METAL SCREW 8 X 2', 'color' => 'A', 'quantity' => 1],
            ['name' => 'METAL SCREW 8 X 2', 'color' => 'HA', 'quantity' => 1],
            ['name' => 'METAL SCREW 6 X 1', 'color' => 'HA', 'quantity' => 1],
            ['name' => 'METAL SCREW 6 X 1/2', 'color' => 'A', 'quantity' => 1],
            ['name' => 'METAL SCREW 6 X 1/2', 'color' => 'A - BY GROSS 2 ', 'quantity' => 1],
            ['name' => 'METAL SCREW 6 X 1', 'color' => 'A', 'quantity' => 6],
            ['name' => 'METAL SCREW 6 X 3/4', 'color' => null, 'quantity' => 1],
            ['name' => 'H-TYPE HANDLE 24" STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'ELBOW 1" 51M STAINLESS', 'color' => 'LONG', 'quantity' => 1],
            ['name' => 'ELBOW 1 1/2" 51M STAINLESS', 'color' => 'LONG', 'quantity' => 1],
            ['name' => 'ELBOW 2" 51M STAINLESS', 'color' => 'SHORT', 'quantity' => 1],
            ['name' => 'ELBOW 2" 51M STAINLESS', 'color' => 'LONG', 'quantity' => 1],
            ['name' => 'FLANGE COVER 1 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'FLANGE COVER 1 1/2 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'FLANGE COVER 2 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'STAINLESS COVER ROUND', 'color' => 'BIG', 'quantity' => 1],
            ['name' => 'STAINLESS COVER ROUND', 'color' => 'SMALL', 'quantity' => 1],
            ['name' => 'STAINLESS COVER SQUARE', 'color' => 'BIG', 'quantity' => 1],
            ['name' => 'STAINLESS COVER SQUARE', 'color' => 'SMALL', 'quantity' => 1],
            ['name' => 'S1', 'color' => null, 'quantity' => 98],
            ['name' => 'S2 STAINLESS', 'color' => 'TOP GRADE', 'quantity' => 98.1],
            ['name' => 'S3', 'color' => null, 'quantity' => 84],
            ['name' => 'UTILITY KNIFE', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'RIVETER', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'MEASURING TAPE', 'color' => 'BIG - TOP GRADE', 'quantity' => 1],
            ['name' => 'MEASURING TAPE (5M)', 'color' => 'SMALL - TOP GRADE', 'quantity' => 6],
            ['name' => 'DRAWER HANDLE OVAL', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'SHOWER ENCLOSURE STAINLESS', 'color' => 'BOX', 'quantity' => 1],
            ['name' => 'STAINLESS ARC HEAVY BIG CURVED BOTTOM GLASS CLIP', 'color' => null, 'quantity' => 1],
            ['name' => 'STAINLESS GLASS CLAMP ANGULAR', 'color' => 'BIG', 'quantity' => 1],
            ['name' => 'TADS-PCL12 D SLIDE WHITE 12"', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'TADS-BB12 D SLIDE FULL 12"', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'STAINLESS GLASS TO GLASS', 'color' => null, 'quantity' => 1],
            ['name' => 'GRINDER STONE', 'color' => null, 'quantity' => 1],
            ['name' => 'GRINDER BLADE', 'color' => null, 'quantity' => 11],
            ['name' => 'STAINLESS DRAWER HANDLE', 'color' => 'TOP GRADE', 'quantity' => 422],
            ['name' => 'STAINLESS DRAWER HANDLE SMALL', 'color' => null, 'quantity' => 10],
            ['name' => 'STAINLESS DRAWER HANDLE C SHAPE', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1/4 SILVER', 'color' => 'SILVER', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1/4 GOLD', 'color' => 'GOLD', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1/2 GOLD', 'color' => 'GOLD - BY 7', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 3/4 SILVER', 'color' => 'SILVER', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 3/4 GOLD', 'color' => 'GOLD', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1" SILVER', 'color' => 'SILVER - DOUBLE', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1" GOLD', 'color' => 'GOLD - DOUBLE', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1" SILVER', 'color' => 'SILVER - SINGLE', 'quantity' => 1],
            ['name' => 'CURTAIN HOLDER 1" GOLD', 'color' => 'GOLD - SINGLE', 'quantity' => 1],
            ['name' => 'CURTAIN CAP 1/2 SILVER', 'color' => 'SILVER', 'quantity' => 1],
            ['name' => 'CURTAIN CAP 1/2 GOLD', 'color' => 'GOLD', 'quantity' => 1],
            ['name' => 'CURTAIN CAP 3/4 SILVER', 'color' => 'SILVER', 'quantity' => 1],
            ['name' => 'CURTAIN CAP 3/4 GOLD', 'color' => 'GOLD', 'quantity' => 1],
            ['name' => 'CURTAIN CAP 1" SILVER', 'color' => 'SILVER', 'quantity' => 1],
            ['name' => 'CURTAIN CAP 1" GOLD', 'color' => 'GOLD', 'quantity' => 1],
            ['name' => 'BULLCASTER BIG', 'color' => null, 'quantity' => 1],
            ['name' => 'BULLCASTER SMALL', 'color' => null, 'quantity' => 1],
            ['name' => 'GLASS HOLDER 1/2', 'color' => null, 'quantity' => 1],
            ['name' => 'GLASS HOLDER #1', 'color' => null, 'quantity' => 1],
            ['name' => 'GLASS HOLDER #2', 'color' => null, 'quantity' => 1],
            ['name' => 'GLASS HOLDER #3', 'color' => null, 'quantity' => 1],
            ['name' => 'GLASS DOOR CLAMP', 'color' => null, 'quantity' => 1],
            ['name' => 'DIAMOND CUTTING WHEEL 4"', 'color' => 'TOP GRADE', 'quantity' => 1],
            ['name' => 'DIAMOND CUTTING', 'color' => 'IRWIN', 'quantity' => 1],
            ['name' => 'BUFFING SOAP', 'color' => null, 'quantity' => 1],
            ['name' => 'SILICON GUN', 'color' => null, 'quantity' => 2],
            ['name' => 'LINE HAMMER', 'color' => null, 'quantity' => 1],
            ['name' => 'STAR SCREW', 'color' => null, 'quantity' => 2],
            ['name' => 'BUFFING DISC #120 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'BUFFING DISC #60 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'BUFFING SOFT #120 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'BUFFING SOFT #60 STAINLESS', 'color' => null, 'quantity' => 1],
            ['name' => 'BALUSTER GLASS CLAMP STAINLESS', 'color' => 'BIG', 'quantity' => 1],
            ['name' => 'BALUSTER GLASS CLAMP STAINLESS', 'color' => 'SMALL', 'quantity' => 1],
            ['name' => 'BAEDAN', 'color' => null, 'quantity' => 3],
            ['name' => 'DRAWER GUIDE #14', 'color' => null, 'quantity' => 5],
            ['name' => 'DRAWER GUIDE #16', 'color' => null, 'quantity' => 60],
            ['name' => 'CUTTER BLADE', 'color' => null, 'quantity' => 11],
            ['name' => 'GLASS CUTTER', 'color' => null, 'quantity' => 10],
        ];

        $skuCounter = 1;

        foreach ($accessories as $accessory) {
            Product::create([
                'name' => $accessory['name'],
                'sku' => 'ACC' . str_pad($skuCounter, 6, '0', STR_PAD_LEFT),
                'category_id' => 7, // Accessories category
                'base_unit' => 'per pc',
                'measurement_unit' => null,
                'default_length' => null,
                'default_width' => null,
                'default_height' => null,
                'color' => $accessory['color'],
                'description' => '',
            ]);

            $skuCounter++;
        }

        $this->command->info('Generated ' . count($accessories) . ' accessories products with SKU starting from ACC000001');
    }
} 