<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class AluminumProductSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            ['name' => 'DOUBLE FLAT SILL', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'DOUBLE FLAT SILL', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'SINGLE FLAT SILL', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'SINGLE FLAT SILL', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'U-GUIDE', 'color' => 'HA', 'base_unit' => 'per pc'],
            ['name' => 'U-GUIDE', 'color' => 'PCW', 'base_unit' => 'per pc'],
            ['name' => 'GLASS DIVIDER', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'GLASS DIVIDER', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'FIXED INTERLOCKER', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'FIXED INTERLOCKER', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'YS 221', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'YS 221', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'Y 221', 'color' => 'WOOD FINISH', 'base_unit' => 'per length'],
            ['name' => 'YS 221 CROSSBAR', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'YS 221 CROSSBAR', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'YS 221 DIVIDER', 'color' => 'HA', 'base_unit' => 'per length'],
            ['name' => 'YS 221 DIVIDER', 'color' => 'PCW', 'base_unit' => 'per length'],
            ['name' => 'SCREEN SILL', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SCREEN SILL', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '21-A', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '21-A', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'JW BUMPER', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'JW BUMPER', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'U-CHANEL', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'U-CHANEL', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'U-CLIP', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'U-CLIP', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'U-CLIP', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'J-CLIP', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'J-CLIP', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/8 ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '3/8 ANGULAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '3/8 ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '1/2 ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1/2 ANGULAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1/2 ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/4 ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '3/4 ANGULAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '3/4 ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '1" ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1" ANGULAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1" ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/4 X 1 ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/4 X 1 ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1 1/2 ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1 1/2 ANGULAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1 1/2 ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '1 3/4 ANGULAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1 3/4 ANGULAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1 3/4 ANGULAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/4 ANGULAR BRACKET', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1 ANGULAR BRACKET', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1 1/2 ANGULAR BRACKET', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1/8 CAHA', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1/8 CAHA', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1/8 CAHA', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/16 CAHA', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '3/16 CAHA', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '3/16 CAHA', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/16 CAHA DOWN', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '3/16 CAHA DOWN', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '3/16 CAHA DOWN', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => '3/8 ROUND TUBE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '3/8 ROUND TUBE', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '5/8 ROUND TUBE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '5/8 ROUND TUBE', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1/2 ROUND TUBE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1/2 ROUND TUBE', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '3/4 ROUND TUBE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '3/4 ROUND TUBE', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1" ROUND TUBE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => '1" ROUND TUBE', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1" ROUND TUBE STAINLESS', 'color' => null, 'base_unit' => 'per length'],
        ['name' => 'ROLLER GUIDE/PLASTIC BEARING', 'color' => null, 'base_unit' => 'per length'],
        ['name' => 'T-RUNNER', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'T-RUNNER', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '3/4 COUNTER NOSING', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => '1/2 COUNTER NOSING', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'PITO GUIDE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'FLAT BAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'FLAT BAR', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'FLAT BAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'U-CHANEL', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'U-CHANEL', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'POLY GUIDE', 'color' => null, 'base_unit' => 'per length'],
        ['name' => 'CLIP W/PLASTIC ROLLER', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'CLIP W/PLASTIC ROLLER', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'SD FIXED STILE', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SD FIXED STILE', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SCREEN FRAME SF101-102', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SCREEN FRAME SF101-102', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SWING SCREEN FRAME', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SWING SCREEN FRAME', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SWING SCREEN CLIP', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SWING SCREEN CLIP', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SCREEN FRAME CROSSBAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SCREEN FRAME CROSSBAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SNAP-ON BASE W/ COVER', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SNAP-ON BASE W/ COVER', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'ALCO FRAME 21FT', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'ALCO FRAME 21FT', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'ALCO FRAME 21FT', 'color' => 'WOOD FINISH', 'base_unit' => 'per length'],
        ['name' => 'ALCO CROSS BAR', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'ALCO CROSS BAR', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'BUS BODY', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'BUS BODY', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'BUS BODY', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'BUS BODY FLAT', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'BUS BODY FLAT', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SCREEN FRAME DOUBLE CANAL', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SCREEN FRAME', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1/2X1', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1/2X1', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X1', 'color' => 'A', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X1', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X1', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X1', 'color' => 'WOOD FINISH', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X2', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X2', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X2', 'color' => 'WOOD FINISH', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X3', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X3', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X3', 'color' => 'WOOD FINISH', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X4', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1X4', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 1X2 X 1', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 1X2 X 1', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 3/4X1 3/4', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 3/4X1 3/4', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 3/4X3', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 3/4X3', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 3/4X4', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'SQ TUBULAR 1 3/4X4', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'PANEL FRAME', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'PANEL FRAME', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'PERIMETER FRAME', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'PERIMETER FRAME', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'MOULDING FRAME', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'MOULDING FRAME', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'I-BAR/CENTER', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'I-BAR/CENTER', 'color' => 'PCW', 'base_unit' => 'per length'],
        ['name' => 'I-BAR W/SCREEN / BYC18', 'color' => 'HA', 'base_unit' => 'per length'],
        ['name' => 'I-BAR W/SCREEN / BYC18', 'color' => 'PCW', 'base_unit' => 'per length'],
        ];

        $skuNumber = 1;

        foreach ($items as $item) {
            Product::create([
                'sku' => 'ALU' . str_pad($skuNumber++, 6, '0', STR_PAD_LEFT),
                'name' => $item['name'],
                'color' => $item['color'] ?? null,
                'category_id' => 10,
                'base_unit' => $item['base_unit'],
                'measurement_unit' => $item['base_unit'] === 'per pc' ? null : 'ft',
                'default_length' => null,
            ]);
        }
    }
}
